config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/trial_exam', to: 'home#trial_exam'

  resources :morse, only: :index do
    get :start, on: :collection
  end

  resources :questions, only: :index do
    post :check, on: :member
    get :start, on: :collection
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/morse_code.rb
# frozen_string_literal: true

class MorseCode < ActiveYaml::Base
  set_root_path 'app/models'
  set_filename 'morse_code'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :topic

  has_many :answers, dependent: :destroy

  def correct_answer
    answers.correct.first
  end
end

app/models/topic.rb
# frozen_string_literal: true

class Topic < ApplicationRecord
  has_many :questions, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
  def trial_exam; end
end

app/controllers/morse_controller.rb
# frozen_string_literal: true

class MorseController < ApplicationController
  def index
    @morse_code = MorseCode.all
  end

  def start
    cookies[:morse_code_level] ||= 0

    @code_by_level = ::TestMorseCode
      .new(level: cookies.fetch(:morse_code_level, 0))
      .start
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def start
    weighting_questions_cookies

    @question = Question.includes(:answers).find(start_question_id)
    @question_ids = Question.where(category: fetch_category).ids
  end

  def check
    @question = Question.find(params.require(:id))
    check_result = @question.correct_answer.id == params[:answer_id].to_i

    if check_result
      weighting_questions_cookies(id: @question.id, correct: true)
      category_params = params[:category] ? { category: params[:category] } : {}
      sleep 0.5
      redirect_to action: :start, **category_params and return
    else
      weighting_questions_cookies(id: @question.id, correct: false)
    end
  end

  private

  helper_method :weight_questions

  def start_question_id
    weight = weight_questions.keys.sort.detect { |k| k.to_i > rand(80) }
    ids = weight_questions.flat_map do |k, v|
      next if weight >= k

      v
    end.compact

    question_ids = Question.where(category: fetch_category).ids
    ((question_ids & ids) | question_ids).sample
  end

  def weighting_questions_cookies(**opts)
    cookies[:weight_questions] ||=
      Base64.encode64({ 80 => [], 70 => [], 50 => [*Question.ids], 40 => [], 30 => [] }.to_json)

    return if opts.empty?

    update_weight_questions(opts)
    cookies[:weight_questions] = Base64.encode64(weight_questions.to_json)
  end

  def update_weight_questions(opts)
    current_weight = weight_questions.detect { |_, v| v.include?(opts[:id]) }[0]
    weight_questions[current_weight].delete(opts[:id])

    if opts[:correct]
      weight_questions[weight_questions.keys.detect { |w| w < current_weight }]&.push(opts[:id])
    else
      weight_questions[weight_questions.keys.sort.detect { |w| w > current_weight }]&.push(opts[:id])
    end
  end

  def weight_questions
    @weight_questions ||= JSON.parse(Base64.decode64(cookies[:weight_questions]))
  end

  def fetch_category
    (params[:category].to_i..4) || [1, 2, 3, 4]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/question_helper.rb
module QuestionHelper
  COLOR_BY_STATUS = {
    '80' => 'red',
    '70' => 'l_red',
    '40' => 'l_green',
    '30' => 'green'
  }.freeze

  def status_question(id)
    COLOR_BY_STATUS[weight_questions.detect { |_, v| v.include?(id) }[0]]
  end
end

app/views/home/index.html.haml
%h2 Инструмент для подготовки к квалификационному экзамену на получение лицензии СЕРТ

app/views/home/trial_exam.html.haml
= render 'shared/start_exam'

.category_list
  %h4 Категории
  %ul.list-group
    %li.list-group-item
      .category_name 1 Категория (эквивалент CEPT T/R 61-01)
      %p Подразумевает сдачу теоретического экзамена на полную лицензию СЕРТ T/R 61-02 с правильными ответами не менее чем на 40 из 45 вопросов в течение 90 минут. Экзамен также включает в себя практическую часть по приёму радиограммы в азбуке Морзе в объёме 250 знаков со скоростью подачи 60 знаков в минуту. Приём должен быть произведён не более чем с тремя ошибками.
    %li.list-group-item
      .category_name 2 Категория (эквивалент CEPT T/R 61-01)
      %p Всё то же самое по той же программе и тем же вопросам, но правильно нужно ответить лишь на 25 вопросов из 30. Знание морзянки здесь уже не потребуется.
    %li.list-group-item
      .category_name 3 Категория (эквивалент CEPT NOVICE)
      %p Подразумевает сдачу теоретического экзамена на лицензию ERC32/ARNEC, с правильными ответами не менее чем на 20 из 25 вопросов в течение 60 минут.
    %li.list-group-item
      .category_name 4 Категория (ECC89)
      %p Подразумевает сдачу теоретического экзамена на лицензию ECC89, с правильными ответами не менее чем на 15 из 20 вопросов в течение 60 минут. Не соответствует какой-либо CEPT-лицензии, и строго говоря, сейчас смысл получать именно её весьма туманен

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Qso
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    .container
      = render 'shared/nav'
      = yield

app/views/morse/index.html.haml
%h2
  Учим Морзе

= link_to 'Учить Код Морзе', start_morse_index_path

%h3 Утилиты
%table.table.morse_utilities
  %thead
    %tr
      %th Linux
      %th Android
  %tbody
    %tr
      %td Cwcp
      %td MorseMania
    %tr
      %td aldo
      %td
    %tr
      %td qrq
      %td
    %tr
      %td cp
      %td

%h3 Телеграфная азбука Морзе (ти – точка, таа – тире)
%table.table.table-bordered.azbuka_morse{ data: { controller: 'morse' } }
  %thead
    %tr{:align => "center"}
      %th{scope: "col"}
        %b Буквы русского алфавита и цифры
      %th{scope: "col"}
        %b Буквы латинского алфавита
      %th{scope: "col"}
        %b Словесное обозначение знака Морзе
      %th{scope: "col"}
        %b Слоговое обозначение знака Морзе
      %th{scope: "col"}
        %b Код Морзе: длительность тире равно длительности трёх точек
  %tbody
    = render @morse_code

app/views/morse/start.html.haml
%h2
  Учим Морзе

%p
  Ваш уровень:
  = cookies[:morse_code_level]

.secret_code_morse{ data: { controller: 'test-morse-code' }}
  .code{ data: { 'test-morse-code': { msg: { value: 'яяя' }}}}
  = @code_by_level
  = button_tag 'Старт', class: 'btn btn-primary', data: { action: "click->test-morse-code#start" }

app/views/morse_codes/_morse_code.html.haml
%tr{:align => "center"}
  %td
    %b= morse_code.ru
  %td= morse_code.en

  %td{:nowrap => "nowrap"}= morse_code.verbal
  %td{:nowrap => "nowrap"}= morse_code.syllabic
  %td
    %a.btn.btn-outline-dark{ data: { action: 'click->morse#play', char: morse_code.ru }}= morse_code.ti_ta

app/views/questions/_form_question.html.haml
= form_with url: check_question_path(@question), class: 'exam_form' do |form|
  = form.hidden_field :category, value: params[:category]
  = form.collection_radio_buttons :answer_id, @question.answers, :id, :title do |b|
    .form-check
      = b.label(class: "form-check-label") { b.radio_button(class: "form-check-input", checked: :checked) + b.text }

  =form.submit 'Ответить', class: 'btn btn-success submit'

app/views/questions/_question.html.haml
%li
  = question.title

app/views/questions/check.turbo_stream.haml
%turbo-stream{ action: "replace", target: dom_id(@question) }
  %template
    %div{ id: dom_id(@question) }
      = form_with url: start_questions_path(category: params[:category]), class: 'exam_form', data: { controller: 'question', choice_answer: "answer_id_#{params[:answer_id]}"} do |form|
        = form.hidden_field :category, value: params[:category]
        = form.collection_radio_buttons :answer_id, @question.answers, :id, :title, { checked: params[:answer_id] } do |b|
          .form-check
            - if @question.correct_answer.id.eql?(b.object.id)
              = b.label(class: "form-check-label", data: { 'question-target' => :correctAnswer }) do
                = b.radio_button(class: "form-check-input") + b.text
            - else
              = b.label(class: "form-check-label") { b.radio_button(class: "form-check-input") + b.text }

        = form.submit 'Далее', class: 'btn btn-success submit'

app/views/questions/index.html.haml
= link_to 'Начать тест', start_questions_path

%h2 Список всех вопросов
%ul
  = render @questions

app/views/questions/start.html.haml
.exam
  %p.current_question= @question.title
  = image_tag "for_exam/#{@question.image}", alt: 'image for question', class: "exam-img" if @question.image

  %p
    Категория вопроса:
    = @question.category
  %div{id: dom_id(@question)}
    = render 'form_question'

  %div.test_passages
    - @question_ids.each do |q_id|
      %div{class: "weight_question question_id-#{q_id} #{status_question(q_id)}"}

app/views/shared/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to 'QSO', root_path, class: 'navbar-brand'

  %ul.navbar-nav.mr-auto
    %li.nav-item.active= link_to 'Пройти тест', trial_exam_path, class: 'navbar-brand'
    %li.nav-item.active= link_to 'Азбука Морзе', morse_index_path, class: 'navbar-brand'

app/views/shared/_start_exam.html.haml
.start-exam{ data: { controller: 'category' } }
  = form_for :category, id: :form_category_exam, data: { 'category-target' => :form } do |form|
    = form.collection_radio_buttons(:category, (1..4).to_a, :to_s, :to_s) do |r|
      .form-check-inline
        = r.label(class: "form-check-label") do
          = r.radio_button(class: "form-check-input", data: { action: "click->category#choice" }) + r.text

  =link_to 'Начать тест', start_questions_path, class: 'btn btn-primary', data: { 'category-target' => :startExamLink }